version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - echo "hello world install"

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - echo "hello world pre build"
      - echo "final testing"
